### PR TITLE
Fixed compatibility with templates editor for Contao 4.9.2

### PR DESCRIPTION
**Pull request by zoglo**
This should fix an issue with the new contao version 4.9.2 where templates can't be edited / not all file extensions are shown.

#118

### CODE REVIEW

**Comment by klimeckt** [comment]
That's working. Thanks.

**Comment by ausi** [comment]
Thank you @zoglo!

I updated the code so that the *_config.php* files can be edited too. Please try the `dev-master` version of the extension and verify if the changes work as expected.

**Comment by zoglo** [comment]
It does work as expected, thank you @ausi

**Comment by ausi** [comment]
Thanks for checking!
Released as version [2.2.15](https://github.com/madeyourday/contao-rocksolid-custom-elements/releases/tag/v2.2.15).

**Pull request merged**
